# Dataset for subgroup discovery

In [5]:
from Serotype_Data import * #Dataset of Serotypes
from Serotype_Functions import *
from PairXPair_dataset import *

#Biopython ver.1.76
from Bio.Seq import Seq #Represent biological sequences with alphabets
from Bio.pairwise2 import format_alignment #Functions to get global and local alignments between two sequences
from Bio import pairwise2

from IPython.display import Image

import numpy as np
import pandas as pd
import tabulate

/home/eunji/workspace/Final_FYP/PairXPair_dataset.py:610: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eli_total_pairgenes_df = eli_total_pairgenes_df_remove_fre.sort_values(by=['Num. of occurrence where pair of sugars processing (without observation)'],

In [6]:
import json
import os

In [7]:
path = os.path.relpath('./serotypes.json')
f = open(path, 'r')
serotypes = json.load(f)

In [8]:
total_pairgenes_df_remove_fre = pd.DataFrame({
    'Pair of genes': li_store_genes, 
    'Pair of sugars': li_store_sugars,
    #'Num. of occurrence of pair of gene (Written in front of each pair of genes)': li_pair_occur,
    'Num. of occurrence where pair of sugars processing (included observation)': li_pair_processing,
    'Num. of occurrence where pair of sugars processing (without observation)': li_pair_processing_without_one,
    'Serotype(s) where processing pair of genes and sugars': li_ser_pair_processing
})

In [9]:
eli_li_store_genes = []#li_store_genes 
eli_li_store_sugars = [] #li_store_sugars
eli_li_pair_processing = [] #li_pair_processing
eli_li_pair_processing_without_one = [] #li_pair_processing_without_one
eli_li_ser_pair_processing = []

single_index = []
for i in range(len(li_ser_pair_processing)):
    # Store index of len(ser_pair_processing)==1
    if len(li_ser_pair_processing[i]) == 1:
        single_index.append(i) 
    
li_indexs = list(range(len(li_store_genes)))
for index in single_index:
    if index in li_indexs:
        li_indexs.remove(index)

for indexs in li_indexs:
    eli_li_store_genes.append(li_store_genes[indexs])
    eli_li_store_sugars.append(li_store_sugars[indexs])
    eli_li_pair_processing.append(li_pair_processing[indexs])
    eli_li_pair_processing_without_one.append(li_pair_processing_without_one[indexs])
    eli_li_ser_pair_processing.append(li_ser_pair_processing[indexs])

In [10]:
eli_total_pairgenes_df_remove_fre = pd.DataFrame({
    'Pair of genes': eli_li_store_genes, 
    'Pair of sugars': eli_li_store_sugars,
    'Num. of occurrence where pair of sugars processing (included observation)': eli_li_pair_processing,
    'Num. of occurrence where pair of sugars processing (without observation)': eli_li_pair_processing_without_one,
    'Serotype(s) where processing pair of genes and sugars': eli_li_ser_pair_processing
})

eli_total_pairgenes_df_remove_fre

,Pair of genes,Pair of sugars,Num. of occurrence where pair of sugars processing (included observation),Num. of occurrence where pair of sugars processing (without observation),Serotype(s) where processing pair of genes and sugars
0,"(rmlA, rmlC)","[glucose, rhamnose]",17,16,"[ser_2, ser_7F, ser_7A, ser_7B, ser_17F, ser_1..."
1,"(rmlA, rmlC)","[rhamnose, rhamnose]",5,4,"[ser_2, ser_7B, ser_17F, ser_17A]"
2,"(rmlA, rmlC)","[rhamnose, glucose]",6,5,"[ser_2, ser_18F, ser_18B, ser_18C, ser_32F, se..."
3,"(rmlA, rmlC)","[glucose, galactose]",6,5,"[ser_6A, ser_6B, ser_17A, ser_18F, ser_18B, se..."
4,"(rmlA, rmlC)","[galactose, ribitol]",2,1,"[ser_6A, ser_6B]"
...,...,...,...,...,...
393,"(wcyH, wcyI)","[rhamnose, glucose]",2,1,"[ser_32F, ser_32A]"
394,"(wcyI, wchQ)","[glucose, rhamnose]",4,3,"[ser_32F, ser_32A]"
395,"(wcyI, wchQ)","[rhamnose, glucose]",2,1,"[ser_32F, ser_32A]"
396,"(wchQ, wcyS)","[glucose, rhamnose]",4,3,"[ser_32F, ser_32A]"
397,"(wchQ, wcyS)","[rhamnose, glucose]",2,1,"[ser_32F, ser_32A]"

In [11]:
eli_total_pairgenes_df_remove_fre.sort_values(by=['Num. of occurrence where pair of sugars processing (without observation)'], 
                                                ascending = False)

,Pair of genes,Pair of sugars,Num. of occurrence where pair of sugars processing (included observation),Num. of occurrence where pair of sugars processing (without observation),Serotype(s) where processing pair of genes and sugars
0,"(rmlA, rmlC)","[glucose, rhamnose]",17,16,"[ser_2, ser_7F, ser_7A, ser_7B, ser_17F, ser_1..."
19,"(rmlC, rmlB)","[glucose, rhamnose]",17,16,"[ser_2, ser_7F, ser_7A, ser_7B, ser_17F, ser_1..."
48,"(rmlB, rmlD)","[glucose, rhamnose]",17,16,"[ser_2, ser_7F, ser_7A, ser_7B, ser_17F, ser_1..."
38,"(wchA, wchF)","[glucose, rhamnose]",17,16,"[ser_2, ser_7F, ser_7A, ser_7B, ser_17F, ser_1..."
203,"(wchJ, wchK)","[glucose, galactose]",10,9,"[ser_11F, ser_11A, ser_11B, ser_11C, ser_13, s..."
...,...,...,...,...,...
169,"(wcjD, ugd)","[glucuronic acid, glucose]",2,1,"[ser_9A, ser_9V]"
168,"(wcjD, ugd)","[galactose, glucuronic acid]",2,1,"[ser_9A, ser_9V]"
167,"(wcjD, ugd)","[N-acetylmannosamine, galactose]",2,1,"[ser_9A, ser_9V]"
166,"(wcjD, ugd)","[glucose, N-acetylmannosamine]",2,1,"[ser_9A, ser_9V]"
397,"(wchQ, wcyS)","[rhamnose, glucose]",2,1,"[ser_32F, ser_32A]"

Let's ignore pairs of genes and corresponding pairs of sugars which appear less than four times.

Cuz which shown one to three times almost shown in each serogroups, so we eliminate them.

In [12]:
condition = eli_total_pairgenes_df_remove_fre['Num. of occurrence where pair of sugars processing (included observation)'] > 3

eli_total_pairgenes_df = eli_total_pairgenes_df_remove_fre.sort_values(by=['Num. of occurrence where pair of sugars processing (without observation)'], 
                                                ascending = False)[condition]

/tmp/ipykernel_28933/2379277838.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eli_total_pairgenes_df = eli_total_pairgenes_df_remove_fre.sort_values(by=['Num. of occurrence where pair of sugars processing (without observation)'],

In [13]:
eli_total_pairgenes_df

,Pair of genes,Pair of sugars,Num. of occurrence where pair of sugars processing (included observation),Num. of occurrence where pair of sugars processing (without observation),Serotype(s) where processing pair of genes and sugars
0,"(rmlA, rmlC)","[glucose, rhamnose]",17,16,"[ser_2, ser_7F, ser_7A, ser_7B, ser_17F, ser_1..."
19,"(rmlC, rmlB)","[glucose, rhamnose]",17,16,"[ser_2, ser_7F, ser_7A, ser_7B, ser_17F, ser_1..."
48,"(rmlB, rmlD)","[glucose, rhamnose]",17,16,"[ser_2, ser_7F, ser_7A, ser_7B, ser_17F, ser_1..."
38,"(wchA, wchF)","[glucose, rhamnose]",17,16,"[ser_2, ser_7F, ser_7A, ser_7B, ser_17F, ser_1..."
203,"(wchJ, wchK)","[glucose, galactose]",10,9,"[ser_11F, ser_11A, ser_11B, ser_11C, ser_13, s..."
...,...,...,...,...,...
63,"(rmlB, rmlD)","[galactose, glucose]",4,3,"[ser_18F, ser_18A, ser_18B, ser_18C]"
64,"(rmlB, rmlD)","[glucose, N-acetylmannosamine]",4,3,"[ser_19F, ser_19A, ser_19B, ser_19C]"
322,"(wchF, wciU)","[galactose, glucose]",4,3,"[ser_18F, ser_18A, ser_18B, ser_18C]"
209,"(wchK, wcyK)","[galactose, galactose]",4,3,"[ser_11F, ser_11A, ser_11B, ser_11C]"
368,"(wchR, wchS)","[N-acetylmannosamine, rhamnose]",4,3,"[ser_19B, ser_19C]"